### ISSUE TITLE
请问作者如何修改代码块的圆角弧度

### ISSUE THREAD

**Issue by devindang** [AntonVanke/Typora-Cement-Theme#1]
使用发现，这个主题的代码块鼠标悬浮和移开的圆角是不一样的，用着很难受，别的地方都超喜欢。请问一下作者，这个要修改什么地方？没有学过css也不知道找哪个部分

**Comment by AntonVanke** [comment]
> 使用发现，这个主题的代码块鼠标悬浮和移开的圆角是不一样的，用着很难受，别的地方都超喜欢。请问一下作者，这个要修改什么地方？没有学过css也不知道找哪个部分

代码块圆角将 `697`-`703` 行删除即可

详见：https://github.com/AntonVanke/Typora-Cement-Theme/blob/main/cement.css#L697-L703

**Comment by devindang** [comment]
> > 使用发现，这个主题的代码块鼠标悬浮和移开的圆角是不一样的，用着很难受，别的地方都超喜欢。请问一下作者，这个要修改什么地方？没有学过css也不知道找哪个部分
> 
> 代码块圆角将 `697`-`703` 行删除即可
> 
> 详见：https://github.com/AntonVanke/Typora-Cement-Theme/blob/main/cement.css#L697-L703

谢谢作者，完美解决。还有一个问题是，release里面的css文件貌似是揉成一团的，只有一行，但是clone下来的css文件就是正常有缩进和换行的，麻烦你确认一下 :)

**Comment by AntonVanke** [comment]
> > > 使用发现，这个主题的代码块鼠标悬浮和移开的圆角是不一样的，用着很难受，别的地方都超喜欢。请问一下作者，这个要修改什么地方？没有学过css也不知道找哪个部分
> > 
> > 
> > 代码块圆角将 `697`-`703` 行删除即可
> > 详见：https://github.com/AntonVanke/Typora-Cement-Theme/blob/main/cement.css#L697-L703
> 
> 谢谢作者，完美解决。还有一个问题是，release里面的css文件貌似是揉成一团的，只有一行，但是clone下来的css文件就是正常有缩进和换行的，麻烦你确认一下 :)

release 我压缩了一下
but 发现压缩没有必要，因为也不是通过网络加载
