### ISSUE TITLE
希望可以调整一下 front-matter 的颜色

### ISSUE THREAD

**Issue by Lingxuan-Ye** [AntonVanke/Typora-Cement-Theme#10]
谢谢你的主题！

希望可以调整一下 front-matter 的颜色，感觉稍微有点刺眼和不协调。

**Comment by Lingxuan-Ye** [comment]
以及「最近使用的文件」部分

**Comment by AntonVanke** [comment]
你指的`front-matter`和`最近使用的文件`是在什么模式下呢？
<暗色模式>？

**Comment by Lingxuan-Ye** [comment]
> 你指的`front-matter`和`最近使用的文件`是在什么模式下呢？ <暗色模式>？

是的
