### ISSUE TITLE
深色模式下文件目录展示问题

### ISSUE THREAD

**Issue by Tiger-zero** [AntonVanke/Typora-Cement-Theme#12]
如图，在深色模式下，当前文件在文件展示目录色彩展示并不是很好，白色背景和白色字体重合，能否调整一下当前两种颜色，使其背景色和字体颜色对比明显。我的建议是能将字体颜色改为黑色，背景为白色，对比明显。
![image](https://user-images.githubusercontent.com/57404601/204098039-65a290d7-9c86-4455-b89b-72c0040a7bf8.png)

**Comment by AntonVanke** [comment]
> 如图，在深色模式下，当前文件在文件展示目录色彩展示并不是很好，白色背景和白色字体重合，能否调整一下当前两种颜色，使其背景色和字体颜色对比明显。我的建议是能将字体颜色改为黑色，背景为白色，对比明显。 ![image](https://user-images.githubusercontent.com/57404601/204098039-65a290d7-9c86-4455-b89b-72c0040a7bf8.png)
是否使用的是最新的版本呢？

我未能重现这个问题
![image](https://user-images.githubusercontent.com/47097086/204121344-888de23e-c3b5-4ad2-b33f-eeded4d40034.png)
![image](https://user-images.githubusercontent.com/47097086/204121368-1c15563f-b0c4-49a5-b092-658b7ee9e0c8.png)

**Comment by Pauluooooo** [comment]
我的也出现了同样的问题，包括菜单页也无法看清，版本为：win64 1.4.8

**Comment by AntonVanke** [comment]
> 我的也出现了同样的问题，包括菜单页也无法看清，版本为：win64 1.4.8

用的是最新的主题?🤔
