### ISSUE TITLE
字体的背景颜色UI样式存在问题

### ISSUE THREAD

**Issue by EricDemon** [AntonVanke/Typora-Cement-Theme#13]
选中时的样式：
<img width="613" alt="image" src="https://user-images.githubusercontent.com/37498873/206069333-5793d5b1-35cf-46df-9ee9-647ba4ca7f09.png">

未选中时的样式：
<img width="630" alt="image" src="https://user-images.githubusercontent.com/37498873/206069291-70eac0de-2ecb-43e1-a08a-fbd5fcb08405.png">

源代码：
<table><tr><td bgcolor=green>背景色Green</td></tr></table>

**Comment by EricDemon** [comment]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/37498873/206069405-fb0369b7-0336-4b96-a045-af10c97bb000.png">

**Comment by AntonVanke** [comment]
我没有考虑到单行表格问题，在单行表格下，就会出现这样的情况

**Comment by EricDemon** [comment]
> 

那可以在下个版本中修复这个问题吗？你的这个主题其他样式太好看了 :)

**Comment by AntonVanke** [comment]
> > 
> 
> 那可以在下个版本中修复这个问题吗？你的这个主题其他样式太好看了 :)

会的

**Comment by EricDemon** [comment]
> 

:) 谢谢
