### ISSUE TITLE
中文字体“思源黑体 CN”不生效

### ISSUE THREAD

**Issue by josephgu41** [AntonVanke/Typora-Cement-Theme#18]
除了这个中文字体之外都生效了，默认的字体太丑了真的受不了了！！有什么办法吗，我已经按要求安装主题了

**Comment by AntonVanke** [comment]
1. 可以使用`release`里的安装脚本试一下
2. 或许是`Windows`环境下没有`HiDPI`的缘故，字体都看的模模糊糊的
     ![image](https://github.com/AntonVanke/Typora-Cement-Theme/assets/47097086/63a8c376-5578-414e-bb9f-6e324e52659a)，可以尝试 [右键] -> [检查元素] 查看是否确实生效
3. 也可能是我遗忘了什么，不过在我这的确生效了

**Comment by josephgu41** [comment]
感谢，用了安装脚本重新装了一遍之后可以了
