### ISSUE TITLE
目录栏与输入页之间的留白空隙

### ISSUE THREAD

**Issue by Tiger-zero** [AntonVanke/Typora-Cement-Theme#4]
![image](https://user-images.githubusercontent.com/57404601/197400717-2c01bf0d-6ece-4246-afbe-36b4c8caa9bc.png)
 您好，是否能够修改这个留白距离？

**Comment by Tiger-zero** [comment]
我个人觉得这个留白太大了，目录的展示似乎也用不到这么大的一个留白，您这个主题，我特别喜欢，感谢您的付出

**Comment by Tiger-zero** [comment]
![image](https://user-images.githubusercontent.com/57404601/197401314-e91db2d2-4039-427d-a24e-10c876002935.png)
我特别喜欢您第一版这个距离

**Comment by AntonVanke** [comment]
> ![image](https://user-images.githubusercontent.com/57404601/197401314-e91db2d2-4039-427d-a24e-10c876002935.png) 我特别喜欢您第一版这个距离

可能是我在适应 A4 纸大小时修改的
等会就会修复
