### ISSUE TITLE
强烈跪求暗色主题

### ISSUE THREAD

**Issue by Alex-coder251** [AntonVanke/Typora-Cement-Theme#6]
😚😚

**Comment by hmpgithub** [comment]
同求

**Comment by Pauluooooo** [comment]
+1

**Comment by AntonVanke** [comment]
已经在改了，但最近较忙，可能需要几天 🤣 
<img width="1082" alt="截屏2022-11-11 21 45 11" src="https://user-images.githubusercontent.com/47097086/201352939-75fbfdd8-3214-456c-99ab-1f7204c76216.png">
