### ISSUE TITLE
希望可以修改代码块字体，以及字体色彩对比

### ISSUE THREAD

**Issue by ok-kai** [AntonVanke/Typora-Cement-Theme#7]
♥😘

**Comment by AntonVanke** [comment]
代码块字体有什么问题呢？

**Comment by ok-kai** [comment]
在win11的21h1版本一些地方默认系统字体还是宋体，显式效果不如您mac上的苹方，配合您扁平化的主题整体有些兀突。

AntonVanke ***@***.***> 于2022年11月5日周六 14:55写道：

**Comment by AntonVanke** [comment]
尝试在 Windows 修改了字体，发现并没有什么变化，可能是某些版本的问题

---

_接下来将会更新_

**Comment by AntonVanke** [comment]
https://github.com/AntonVanke/Typora-Cement-Theme/releases/tag/v0.2.13

可以看看是否有改善

**Comment by ok-kai** [comment]
感谢回复，注释字体依旧.

AntonVanke ***@***.***> 于2022年11月6日周日 21:55写道：
