### ISSUE TITLE
Right click menu hard to read

### ISSUE THREAD

**Issue by Lambert-Rao** [AntonVanke/Typora-Cement-Theme#9]
![image](https://user-images.githubusercontent.com/101875596/201795923-24ad77d9-d79e-4633-9004-fa50b2abd2c5.png)
亮色模式下右键菜单看不清文字，建议改成浅色背景
In bright theme, the text is difficult to read, i suggest to use a bright blackboard

**Comment by AntonVanke** [comment]
🤔添加深色背景时改错误了
